// <auto-generated />
using System;
using Accounting.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Accounting.Infrastructure.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20251014052853_AddPurchase")]
    partial class AddPurchase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acc")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Accounting.Infrastructure.DonMua", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CoHopDongLon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("co_hop_dong_lon");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<DateTime>("NgayDon")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_don");

                    b.Property<long>("NhaCungCapId")
                        .HasColumnType("bigint")
                        .HasColumnName("nha_cung_cap_id");

                    b.Property<string>("SoCt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("so_ct");

                    b.Property<decimal>("TienHang")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tien_hang");

                    b.Property<string>("TienTe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tien_te");

                    b.Property<decimal>("TienThue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tien_thue");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("nhap")
                        .HasColumnName("trang_thai");

                    b.Property<decimal>("TyGia")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasDefaultValue(1.0000m)
                        .HasColumnName("ty_gia");

                    b.HasKey("Id");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("SoCt")
                        .IsUnique();

                    b.ToTable("don_mua", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.DonMuaDong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("DinhLuongGsm")
                        .HasColumnType("int")
                        .HasColumnName("dinh_luong_gsm");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia");

                    b.Property<long>("DonMuaId")
                        .HasColumnType("bigint")
                        .HasColumnName("don_mua_id");

                    b.Property<string>("GiaCong")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gia_cong");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kich_thuoc");

                    b.Property<string>("LoaiGiay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loai_giay");

                    b.Property<string>("MauIn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mau_in");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("so_luong");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanh_tien");

                    b.Property<long?>("ThueSuatId")
                        .HasColumnType("bigint")
                        .HasColumnName("thue_suat_id");

                    b.Property<decimal>("TienThue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tien_thue");

                    b.Property<long>("VatTuId")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_tu_id");

                    b.HasKey("Id");

                    b.HasIndex("DonMuaId");

                    b.HasIndex("ThueSuatId");

                    b.HasIndex("VatTuId");

                    b.ToTable("don_mua_dong", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.DonViTinh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("don_vi_tinh", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.HoaDonMua", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("DonMuaId")
                        .HasColumnType("bigint")
                        .HasColumnName("don_mua_id");

                    b.Property<DateTime?>("HanThanhToan")
                        .HasColumnType("datetime2")
                        .HasColumnName("han_thanh_toan");

                    b.Property<DateTime>("NgayHoaDon")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_hoa_don");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<long>("NhaCungCapId")
                        .HasColumnType("bigint")
                        .HasColumnName("nha_cung_cap_id");

                    b.Property<string>("SoCt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("so_ct");

                    b.Property<decimal>("TienHang")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tien_hang");

                    b.Property<decimal>("TienThue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tien_thue");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("con_no")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("DonMuaId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("SoCt")
                        .IsUnique();

                    b.ToTable("hoa_don_mua", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.HoaDonMuaDong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia");

                    b.Property<long>("HoaDonMuaId")
                        .HasColumnType("bigint")
                        .HasColumnName("hoa_don_mua_id");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("so_luong");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanh_tien");

                    b.Property<long?>("ThueSuatId")
                        .HasColumnType("bigint")
                        .HasColumnName("thue_suat_id");

                    b.Property<decimal>("TienThue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tien_thue");

                    b.Property<long>("VatTuId")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_tu_id");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonMuaId");

                    b.HasIndex("ThueSuatId");

                    b.HasIndex("VatTuId");

                    b.ToTable("hoa_don_mua_dong", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.KhachHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ma_so_thue");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_cap_nhat");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("khach_hang", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.Kho", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_cap_nhat");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("kho", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.NhaCungCap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ma_so_thue");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_cap_nhat");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("nha_cung_cap", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.PhieuNhap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("DonMuaId")
                        .HasColumnType("bigint")
                        .HasColumnName("don_mua_id");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<long>("KhoId")
                        .HasColumnType("bigint")
                        .HasColumnName("kho_id");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhap");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<long?>("NhaCungCapId")
                        .HasColumnType("bigint")
                        .HasColumnName("nha_cung_cap_id");

                    b.Property<string>("SoCt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("so_ct");

                    b.HasKey("Id");

                    b.HasIndex("DonMuaId");

                    b.HasIndex("KhoId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("SoCt")
                        .IsUnique();

                    b.ToTable("phieu_nhap", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.PhieuNhapDong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia");

                    b.Property<decimal>("GiaTri")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_tri");

                    b.Property<long>("PhieuNhapId")
                        .HasColumnType("bigint")
                        .HasColumnName("phieu_nhap_id");

                    b.Property<string>("SoLo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_lo");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("so_luong");

                    b.Property<long>("VatTuId")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_tu_id");

                    b.HasKey("Id");

                    b.HasIndex("PhieuNhapId");

                    b.HasIndex("VatTuId");

                    b.ToTable("phieu_nhap_dong", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.TaiKhoanNganHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_tai_khoan");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_ngan_hang");

                    b.Property<string>("TienTe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("VND")
                        .HasColumnName("tien_te");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("tai_khoan_ngan_hang", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.ThueSuat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DangHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("dang_hoat_dong");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten");

                    b.Property<decimal>("TyLe")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("ty_le");

                    b.HasKey("Id");

                    b.ToTable("thue_suat", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.VatTu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<int?>("DinhLuongGsm")
                        .HasColumnType("int")
                        .HasColumnName("dinh_luong_gsm");

                    b.Property<long?>("DonViTinhId")
                        .HasColumnType("bigint")
                        .HasColumnName("don_vi_tinh_id");

                    b.Property<string>("GiaCong")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gia_cong");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kich_thuoc");

                    b.Property<string>("LoaiGiay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loai_giay");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<string>("MauIn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mau_in");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_cap_nhat");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhId");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("vat_tu", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.DonMua", b =>
                {
                    b.HasOne("Accounting.Infrastructure.NhaCungCap", null)
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Infrastructure.DonMuaDong", b =>
                {
                    b.HasOne("Accounting.Infrastructure.DonMua", null)
                        .WithMany()
                        .HasForeignKey("DonMuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounting.Infrastructure.ThueSuat", null)
                        .WithMany()
                        .HasForeignKey("ThueSuatId");

                    b.HasOne("Accounting.Infrastructure.VatTu", null)
                        .WithMany()
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Infrastructure.HoaDonMua", b =>
                {
                    b.HasOne("Accounting.Infrastructure.DonMua", null)
                        .WithMany()
                        .HasForeignKey("DonMuaId");

                    b.HasOne("Accounting.Infrastructure.NhaCungCap", null)
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Infrastructure.HoaDonMuaDong", b =>
                {
                    b.HasOne("Accounting.Infrastructure.HoaDonMua", null)
                        .WithMany()
                        .HasForeignKey("HoaDonMuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounting.Infrastructure.ThueSuat", null)
                        .WithMany()
                        .HasForeignKey("ThueSuatId");

                    b.HasOne("Accounting.Infrastructure.VatTu", null)
                        .WithMany()
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Infrastructure.PhieuNhap", b =>
                {
                    b.HasOne("Accounting.Infrastructure.DonMua", null)
                        .WithMany()
                        .HasForeignKey("DonMuaId");

                    b.HasOne("Accounting.Infrastructure.Kho", null)
                        .WithMany()
                        .HasForeignKey("KhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounting.Infrastructure.NhaCungCap", null)
                        .WithMany()
                        .HasForeignKey("NhaCungCapId");
                });

            modelBuilder.Entity("Accounting.Infrastructure.PhieuNhapDong", b =>
                {
                    b.HasOne("Accounting.Infrastructure.PhieuNhap", null)
                        .WithMany()
                        .HasForeignKey("PhieuNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounting.Infrastructure.VatTu", null)
                        .WithMany()
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Infrastructure.VatTu", b =>
                {
                    b.HasOne("Accounting.Infrastructure.DonViTinh", null)
                        .WithMany()
                        .HasForeignKey("DonViTinhId");
                });
#pragma warning restore 612, 618
        }
    }
}
