// <auto-generated />
using System;
using Accounting.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Accounting.Infrastructure.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20251014045753_AddCatalog")]
    partial class AddCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acc")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Accounting.Infrastructure.DonViTinh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("don_vi_tinh", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.KhachHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ma_so_thue");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_cap_nhat");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("khach_hang", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.Kho", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_cap_nhat");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("kho", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.NhaCungCap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ma_so_thue");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_cap_nhat");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("nha_cung_cap", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.TaiKhoanNganHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_tai_khoan");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_ngan_hang");

                    b.Property<string>("TienTe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("VND")
                        .HasColumnName("tien_te");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("tai_khoan_ngan_hang", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.ThueSuat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DangHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("dang_hoat_dong");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten");

                    b.Property<decimal>("TyLe")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("ty_le");

                    b.HasKey("Id");

                    b.ToTable("thue_suat", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.VatTu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<int?>("DinhLuongGsm")
                        .HasColumnType("int")
                        .HasColumnName("dinh_luong_gsm");

                    b.Property<long?>("DonViTinhId")
                        .HasColumnType("bigint")
                        .HasColumnName("don_vi_tinh_id");

                    b.Property<string>("GiaCong")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gia_cong");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kich_thuoc");

                    b.Property<string>("LoaiGiay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loai_giay");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma");

                    b.Property<string>("MauIn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mau_in");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_cap_nhat");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhId");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("vat_tu", "acc");
                });

            modelBuilder.Entity("Accounting.Infrastructure.VatTu", b =>
                {
                    b.HasOne("Accounting.Infrastructure.DonViTinh", null)
                        .WithMany()
                        .HasForeignKey("DonViTinhId");
                });
#pragma warning restore 612, 618
        }
    }
}
